#!/usr/bin/env bash
# displays badluck frm China for the 4th loop
# displays badluck frm Japan for the 9th loop
# displays badluck from Italy for the 17 loop

count=1
while [ $count -le 20 ]
do
echo "$count"
case $count in
"4") echo "bad luck from China";;
"9") echo "bad luck from Japan";;
"17") echo "bad luck from Italy";;
esac
((count++))
done
