#!/usr/bin/env bash
# displays hours from 0 to 12
# displays min from 1 to 59

hour=0
while [ $hour -le 12 ]
do
echo "Hour: $hour"
mins=1
while [ $mins -le 59 ]
do
echo "$mins"
(( mins++ ))
done
(( hour++ ))
done
